/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainlinkFeed } from "./ChainlinkFeed";
export type { FeedPriceOracleV2 } from "./FeedPriceOracleV2";
export type { IStdReference } from "./IStdReference";
export type { WitnetFeed } from "./WitnetFeed";
