/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UnderwriterAdminInterface,
  UnderwriterAdminInterfaceInterface,
} from "../../../contracts/Comptroller.sol/UnderwriterAdminInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "cToken",
        type: "address",
      },
    ],
    name: "_getBorrowPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cToken",
        type: "address",
      },
    ],
    name: "_getMarketBorrowCap",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cToken",
        type: "address",
      },
    ],
    name: "_getMintPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "_getSeizePaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "_getSuTokenRateMantissa",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "_getTransferPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCompAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "groupId",
        type: "uint8",
      },
    ],
    name: "getEqAssetGroup",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "groupId",
            type: "uint8",
          },
          {
            internalType: "string",
            name: "groupName",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "inGroupCTokenRateMantissa",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "inGroupSuTokenRateMantissa",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "interGroupCTokenRateMantissa",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "interGroupSuTokenRateMantissa",
            type: "uint256",
          },
        ],
        internalType: "struct UnderwriterAdminInterface.EqualAssets",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEqAssetGroupNum",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class UnderwriterAdminInterface__factory {
  static readonly abi = _abi;
  static createInterface(): UnderwriterAdminInterfaceInterface {
    return new utils.Interface(_abi) as UnderwriterAdminInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UnderwriterAdminInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UnderwriterAdminInterface;
  }
}
