/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ChainlinkFeed__factory } from "./ChainlinkFeed__factory";
export { FeedPriceOracleV2__factory } from "./FeedPriceOracleV2__factory";
export { IStdReference__factory } from "./IStdReference__factory";
export { WitnetFeed__factory } from "./WitnetFeed__factory";
